version: '3.1'
services:
  mongo:
    image: bitnami/mongodb:5.0.15
    restart: always
    container_name: tdd-mongo
    volumes:
      - "mongodb_data:/bitnami/mongodb"
    env_file:
      - .env
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      - BITNAMI_DEBUG=1
    ports:
      - "27018:27017"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    restart: always

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  mongodb_data:
    driver: local