imports:
  - { resource: ./application.yaml }
services:
  User.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/typeorm/typeorm.environment.arranger
    arguments: ['@User.ConnectionManager']