services:

  Apps.user.controllers.StatusGetController:
    class: ../../controllers/status.get.controller
    arguments: []

  Apps.user.controllers.UserPutController:
    class: ../../controllers/user.put.controller
    arguments: ['@User.users.application.UserCreator']

  Apps.mooc.controllers.UsersCounterGetController:
    class: ../../controllers/users.counter.get.controller
    arguments: [ "@Mooc.UsersCounter.UsersCounterFinder" ]

