services:
  User.TypeOrmConfig:
    factory:
      class: ../../../../../contexts/user/shared/infrastructure/persistence/typeorm/typeorm.client.factory
      method: 'createConfig'

  User.ConnectionManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/typeorm/typeorm.client.factory
      method: 'createClient'
    arguments: [ 'user', '@User.TypeOrmConfig' ]

  User.users.domain.UserRepository:
    class: ../../../../../contexts/user/users/infrastructure/persistence/typeorm.user.repository
    arguments: ['@User.ConnectionManager']
    #class: ../../../../../contexts/user/users/infrastructure/persistence/file.user.repository
    #arguments: [""]


  User.users.application.UserCreator:
    class: ../../../../../contexts/user/users/application/user.creator
    arguments: ['@User.users.domain.UserRepository', '@User.shared.domain.EventBus']

  User.courses.CreateCourseCommandHandler:
    class: ../../../../../contexts/user/users/application/create.user.command.handler
    arguments: [ '@User.users.application.UserCreator' ]
    tags:
      - { name: 'commandHandler' }