services:
  Shared.Logger:
    class: ../../../../../contexts/shared/infrastructure/winston.logger
    arguments: []


  Backoffice.Shared.MongoConfig:
  factory:
    class: ../../../../../contexts/user/shared/infrastructure/persistence/mongo/mongo.config.factory
    method: 'createConfig'

  Backoffice.Shared.ConnectionManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/mongo/mongo.client.factory
      method: 'createClient'
    arguments: ['backoffice', '@Backoffice.Shared.MongoConfig']

  Backoffice.Shared.CommandHandlers:
    class: ../../../../../contexts/shared/infrastructure/command-bus/command.handlers
    arguments: ['!tagged commandHandler']

  Backoffice.Shared.domain.CommandBus:
    class: ../../../../../Contexts/shared/infrastructure/command-bus/in.memory.command.bus
    arguments: ['@Backoffice.Shared.CommandHandlers']

  Backoffice.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../Contexts/user/shared/infrastructure/rabbitmq/rabbitmq.config.factory
      method: 'createConfig'

  Backoffice.Shared.domain.EventBus:
    factory:
      class: ../../../../../Contexts/user/shared/infrastructure/rabbitmq/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Backoffice.Shared.DomainEventFailoverPublisher',
        '@Backoffice.Shared.RabbitMQConnection',
        '@Backoffice.Shared.RabbitMQqueueFormatter',
        '@Backoffice.Shared.RabbitMQConfig'
      ]

  Backoffice.Shared.RabbitMQQueueFormatter:
    class: ../../../../../Contexts/shared/infrastructure/EventBus/rabbitmq/RabbitMQqueueFormatter
    arguments: ['backoffice']

  Backoffice.Shared.RabbitMQConnection:
    class: ../../../../../Contexts/shared/infrastructure/EventBus/rabbitmq/RabbitMqConnection
    arguments: ['@Backoffice.Shared.RabbitMQConfig']

  Backoffice.Shared.RabbitMQqueueFormatter:
    class: ../../../../../Contexts/shared/infrastructure/EventBus/rabbitmq/RabbitMQqueueFormatter
    arguments: ['backoffice']

  Backoffice.Shared.DomainEventFailoverPublisher:
    class: ../../../../../Contexts/shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Backoffice.Shared.ConnectionManager']

  Backoffice.Shared.QueryHandlers:
    class: ../../../../../contexts/shared/infrastructure/query-bus/query.handlers
    arguments: [ '!tagged queryHandler' ]

  Backoffice.Shared.domain.QueryBus:
    class: ../../../../../contexts/shared/infrastructure/query-bus/in.memory.query.bus
    arguments: [ '@Backoffice.Shared.QueryHandlers' ]