services:
  User.UsersCounter.UsersCounterRepository:
    class: ../../../../../contexts/user/users-counter/infrastructure/persistence/mongo/mongo.users.counter.repository
    arguments: ["@User.Shared.ConnectionManager"]

  User.UsersCounter.UsersCounterIncrementer:
    class: ../../../../../contexts/user/users-counter/application/increment/users.counter.incrementer
    arguments: [
      "@User.UsersCounter.UsersCounterRepository",
      "@User.Shared.domain.EventBus"
      ]

  User.UsersCounter.IncrementUsersCounterOnCourseCreated:
    class: ../../../../../contexts/user/users-counter/application/increment/increment.users.counter.on.user.created
    arguments: ["@User.UsersCounter.UsersCounterIncrementer"]
    tags:
      - { name: 'domainEventSubscriber' }

  User.UsersCounter.UsersCounterFinder:
    class: ../../../../../contexts/user/users-counter/application/find/users.counter.finder
    arguments: ["@User.UsersCounter.UsersCounterRepository"]


