services:
  Mooc.UsersCounter.UsersCounterRepository:
    class: ../../../../../contexts/mooc/users-counter/infrastructure/persistence/mongo/mongo.users.counter.repository
    arguments: ["@Mooc.Shared.ConnectionManager"]

  Mooc.UsersCounter.UsersCounterIncrementer:
    class: ../../../../../contexts/mooc/users-counter/application/increment/users.counter.incrementer
    arguments: [
      "@Mooc.UsersCounter.UsersCounterRepository",
      "@Mooc.Shared.domain.EventBus"
      ]

  Mooc.UsersCounter.IncrementUsersCounterOnCourseCreated:
    class: ../../../../../contexts/mooc/users-counter/application/increment/increment.users.counter.on.user.created
    arguments: ["@Mooc.UsersCounter.UsersCounterIncrementer"]
    tags:
      - { name: 'domainEventSubscriber' }

  Mooc.UsersCounter.UsersCounterFinder:
    class: ../../../../../contexts/mooc/users-counter/application/find/users.counter.finder
    arguments: ["@Mooc.UsersCounter.UsersCounterRepository"]


